apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-control-sa
  namespace: access-control
  labels:
    app: access-control-api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-control-role
  namespace: access-control
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-control-rolebinding
  namespace: access-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-control-role
subjects:
  - kind: ServiceAccount
    name: access-control-sa
    namespace: access-control
